@startuml Фреймовая_модель_АСОИУ_преподаватели
title Фреймовая модель: Преподаватели магистратуры кафедры АСОИУ (ИИТиК, АГТУ)

skinparam classAttributeIconSize 0
skinparam shadowing true
skinparam roundcorner 15
skinparam style strictuml


class Преподаватель #LightBlue {
-- Общая информация --
  - ФИО
  - институт
  - кафедра
  - должность
-- Образование и статус --
  - уровень (уровни) профессионального образования
  - учёная степень
  - учёное звание
-- Учебная нагрузка --
  - курсы
}

' === Наследование ===
class "Попов" extends Преподаватель
class "Хоменко" extends Преподаватель
class "Белов" extends Преподаватель

' === Фреймы: Преподаватели ===
class "Попов" #Wheat {
-- Общая информация --
  ФИО = Попов Георгий Александрович
  институт = ИИТиК
  кафедра = ИНФОРМАЦИОННАЯ БЕЗОПАСНОСТЬ
  должность = ПРОФЕССОР, Д/Н - ПРОФЕССОР КАФЕДРЫ "ИНФОРМАЦИОННАЯ БЕЗОПАСНОСТЬ"
-- Образование и статус --
  проф.образование = Высшее образование - специалитет, МАТЕМАТИК
  уч.степень = Доктор технических наук
  уч.звание = ПРОФЕССОР по кафедре "Математика и крипторгафия"
-- Учебная нагрузка --
  курсы = [Интеллектуальные системы, Задачи анализа данных]
-- Процедурные слоты --
  if-needed курс: выбрать преподавателя по экспертным системам
  if-added курс: пересчитать нагрузку кафедры
}

class "Хоменко" #Moccasin {
-- Общая информация --
  ФИО = Хоменко Татьяна Владимировна
  институт = ИИТиК
  кафедра = АСОИУ
  должность = заведующий кафедрой, Д/Н - ДОЦЕНТ кафедры "АСОИУ"
-- Образование и статус --
  проф.образование = Высшее образование - специалитет, учитель математики и физики
  уч.степень = Доктор технических наук
  уч.звание = ДОЦЕНТ по кафедре "Математика"
-- Учебная нагрузка --
  курсы = [Методы оптимизации]
-- Процедурные слоты --
  if-added курс: направить уведомление в учебный отдел
  if-needed курс: запросить квалификацию по системному анализу
}

class "Белов" #LightYellow {
-- Общая информация --
  ФИО = Белов Сергей Валерьевич
  институт = ИИТиК
  кафедра = АСОИУ
  должность = ДИРЕКТОР ИНСТИТУТА, К/Н - ДОЦЕНТ ДИРЕКТОРАТА "ИИТиК"
-- Образование и статус --
  проф.образование = Высшее образование - специалитет, ИНЖЕНЕР
  уч.степень = Кандидат технических наук
  уч.звание = ДОЦЕНТ по кафедре "Информационная безопасность"
-- Учебная нагрузка --
  курсы = [ИИ на Python]
}

@enduml
