@startuml Фреймовая_модель_АСОИУ_направление
title Фреймовая модель: Направления кафедры АСОИУ (ИИТиК, АГТУ)

skinparam classAttributeIconSize 0
skinparam shadowing true
skinparam roundcorner 15
skinparam style strictuml

class Направление #LightBlue {
-- Общая информация --
  - код
  - название
  - направленность
  - уровень подготовки
  - форма и сроки обучения
-- Академический состав --
  - кафедра выпускающая
  - курсы
  - студенты
}

' === Наследование ===
class "Магистратура ИВТ" extends Направление
class "Программная инженерия" extends Направление

' === Фреймы: Курсы ===
class "Магистратура ИВТ" #LightYellow {
-- Общая информация --
  код = 09.04.01
  название = Информатика и вычислительная техника
  направленность = Искусственный интеллект в автоматизации проектирования
  уровень подготовки = магистратура
  форма и сроки обучения = очная — 2 года, заочная — 2.5 лет
-- Академический состав --
  кафедра = АСОИУ
  курсы = [Интеллектуальные системы, Задачи анализа данных, Методы оптимизации, ИИ на Python]
  студенты = [Никифорова О.В., Назарова А.Г.]
}

class "Программная инженерия" #Moccasin {
-- Общая информация --
  код = 09.03.04
  название = Программная инженерия
  направленность = Разработка программно-информационных систем
  уровень подготовки = бакалавриат
  форма и сроки обучения = очная — 4 года, заочная — 5 лет
-- Академический состав --
  кафедра = АСОИУ
  курсы = [Основы ООП, Разработка на Java]
  студенты = [Иванов В.К., Колосов А.Б.]
}

@enduml
