@startuml Фреймовая_модель_АСОИУ_кафедра
title Фреймовая модель: Кафедра (ИИТиК, АГТУ)

skinparam classAttributeIconSize 0
skinparam shadowing true
skinparam roundcorner 15
skinparam style strictuml

class Кафедра #LightBlue {
-- Основное --
  - название
  - институт
-- Состав --
  - преподаватели
  - направления подготовки
-- Функции --
  - организует курсы
}

' === Наследование ===
class "АСОИУ" extends Кафедра

' === Фреймы: Кафедра ===
class "АСОИУ" #LightYellow {
-- Основное --
  название = Автоматизированные системы обработки информации и управления
  институт = ИИТиК
-- Состав --
  преподаватели = [Попов Г.А., Хоменко Т.В., Белов С.В.]
  направления = [Бакалавриат 09.03.04 «Программная инженерия», Магистратура 09.04.01 ИВТ]
-- Функции --
  курсы = [Интеллектуальные системы, Задачи анализа данных, Методы оптимизации, ИИ на Python]
}

@enduml
