@startuml Фреймовая_модель_АСОИУ_студенты
title Фреймовая модель: Студенты магистратуры кафедры АСОИУ (ИИТиК, АГТУ)

skinparam classAttributeIconSize 0
skinparam shadowing true
skinparam roundcorner 15
skinparam style strictuml

class Студент #LightBlue {
-- Личные данные --
  - ФИО

-- Принадлежность --
  - институт
  - кафедра
  - направление

-- Академическая информация --
  - курсы
  - дипломный руководитель
  - год поступления
  - форма обучения
}

' === Наследование ===
class "Никифорова" extends Студент
class "Назарова" extends Студент

' === Фреймы: Студенты ===
class "Никифорова" #LightYellow {
-- Личные данные --
  ФИО = Никифорова Оксана Владимировна
-- Принадлежность --
  институт = ИИТиК
  кафедра = АСОИУ
  направление = 09.04.01 ИВТ
-- Академическая информация --
  курсы = [Интеллектуальные системы, Задачи анализа данных, Методы оптимизации, ИИ на Python]
  дипломный руководитель = Хоменко Т.В.
  год поступления = 2024
  форма обучения = заочная

-- Процедурные слоты --
  if-added курс: пересчитать учебную нагрузку
  if-needed дипломный руководитель: выбрать по профилю курсов
}


class "Назарова" #Moccasin {
-- Личные данные --
  ФИО = Назарова Анна Геннадьевна
-- Принадлежность --
  институт = ИИТиК
  кафедра = АСОИУ
  направление = 09.04.01 ИВТ
-- Академическая информация --
  курсы = [Интеллектуальные системы, Задачи анализа данных, Методы оптимизации, ИИ на Python]
  дипломный руководитель = Попов Г.А.
  год поступления = 2024
  форма обучения = заочная
-- Процедурные слоты --
  if-added курс: уведомить куратора
  if-needed дипломный руководитель: выбрать по интересам студента
}

@enduml
